<font color='red'><b>**WARNING**</b></font> <br/>
어떠한 사유로도 임의로 복사, 촬영, 녹음, 복제, 보관, 전송하거나 허가 받지 않은 저장매체를 이용한 보관, 제3자에게 누설, 공개 또는 사용하는 등의 무단 사용 및 불법 배포 시 법적 조치를 받을 수 있습니다. <br/>

<div style="text-align: right; color: #7f8c8d; font-size: 0.9em; margin-top: 20px;">
📝 Author: 박사홍 (Sahong Pak)</br>
📧 Contact: sahong.pak@gmail.com</br>
📌 Version: v2.0</br>
📅 Last Updated: 2026-03-12</br>
</div>

</br>

# 학습 내용
>이번 장에서는 <strong>NumPy 기초(NumPy Fundamentals)</strong>에 대해 학습합니다.</br></br>
>다차원 배열(ndarray)의 생성, 인덱싱, 연산, 브로드캐스팅을 학습해봅시다.

</br>

In [2]:
# TODO 0: 실습을 위해 numpy 모듈을 추가하고 별칭을 np로 설정해봅시다.
import numpy as np

</br>

# NumPy 배열 (ndarray)
> NumPy는 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">고성능 다차원 배열(ndarray)</mark>을 제공하는 수치 연산 라이브러리입니다.</br>
> Python 리스트보다 메모리 효율적이고 연산 속도가 빠릅니다.

>Python 리스트로 백만 개의 숫자를 2배로 만들려면 `for` 반복문이 필요합니다. 느립니다.</br>
>NumPy는 같은 작업을 `arr * 2` 한 줄로, <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">내부적으로 C 언어 수준의 속도</mark>로 처리합니다.</br>
>실제 벤치마크에서 NumPy는 Python 리스트보다 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">수십 배에서 100배 이상 빠릅니다</mark>.</br>
>메모리 측면에서도 Python 리스트는 각 숫자를 객체로 저장하지만, NumPy 배열은 연속된 메모리 블록에 순수 숫자만 저장하여 훨씬 적은 메모리를 사용합니다.

><mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">벡터화</mark>란 반복문 없이 배열 전체에 한 번에 연산을 적용하는 방식입니다.</br>
머신러닝에서 가중치 업데이트, 데이터 정규화, 행렬 곱셈 등의 연산은 수백만 번 반복되는데, Python `for` 루프로는 이런 연산이 실용적인 시간 안에 끝나지 않습니다.</br>
>NumPy의 벡터화 연산은 Pandas, TensorFlow, scikit-learn 등 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">데이터 과학 생태계 전체의 기반</mark>이며, NumPy를 이해하면 이 도구들의 동작 방식을 훨씬 깊이 이해할 수 있습니다.

In [7]:
# TODO 1: array에 [1, 2, 3, 4, 5]를, matrix에 [[1, 2, 3], [4, 5, 6]]을 NumPy 배열로 저장하고, 각 배열과 shape를 출력해봅시다.

# 1. 1차원 배열(Vector) 생성
# array = [1, 2, 3, 4, 5] # 파이썬의 리스트
array = np.array([1, 2, 3, 4, 5]) # NumPy 리스트?

# 2. 2차원 행렬(Matrix) 생성
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

# 3. 결과 출력
print("--- 1차원 Array ---")
print(f"내용: {array}")
print(f"Shape: {array.shape}")  # (5,) 1행 5열 출력
print(f"차원 수 (ndim): {array.ndim}")  # 1 차원 수 확인

print("\n--- 2차원 Matrix ---")
print(f"내용:\n{matrix}")
print(f"Shape: {matrix.shape}") # (2, 3) 2행 3열 출력
print(f"차원 수 (ndim): {matrix.ndim}")  # 2 차원 수 확인

--- 1차원 Array ---
내용: [1 2 3 4 5]
Shape: (5,)
차원 수 (ndim): 1

--- 2차원 Matrix ---
내용:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
차원 수 (ndim): 2


</br>

## 배열 속성

<table style="width:100%">
  <thead>
    <tr>
      <th style="text-align:center">속성</th>
      <th>설명</th>
      <th>예시</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="text-align:center"><code>shape</code></td><td>차원별 크기</td><td><code>(2, 3)</code></td></tr>
    <tr><td style="text-align:center"><code>ndim</code></td><td>차원 수</td><td><code>2</code></td></tr>
    <tr><td style="text-align:center"><code>dtype</code></td><td>데이터 타입</td><td><code>float64</code></td></tr>
    <tr><td style="text-align:center"><code>size</code></td><td>전체 요소 수</td><td><code>6</code></td></tr>
  </tbody>
</table>

</br>

## 배열 생성 함수

<table style="width:100%">
  <thead>
    <tr>
      <th style="text-align:center">함수</th>
      <th>설명</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="text-align:center"><code>np.zeros(shape)</code></td><td>모든 원소가 0인 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.arange(start, stop, step)</code></td><td>시작~끝(미포함)까지 step 간격의 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.linspace(start, stop, num)</code></td><td>시작~끝(포함)을 num개로 균등 분할한 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.ones(shape)</code></td><td>모든 원소가 1인 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.full(shape, val)</code></td><td>특정 값으로 채운 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.eye(n)</code></td><td>n×n 단위행렬(대각선이 1) 생성</td></tr>
    <tr><td style="text-align:center"><code>np.random.randint(low, high, size)</code></td><td>범위 내 랜덤 정수 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.random.randn(d0, d1, ...)</code></td><td>표준정규분포 난수 배열 생성</td></tr>
  </tbody>
</table>

In [8]:
# TODO 2: 모든 원소가 0인 2x3 행렬, 0부터 10까지 2간격 행렬, 0부터 1사이를 5개로 균등하게 나눈 행렬을 출력해봅시다.
# 1. 모든 원소가 0인 2x3 행렬
# zeros() 안에는 모양(shape)을 튜플 형태로 넣어줍니다.
zeros_matrix = np.zeros((2, 3))

# 2. 0부터 10까지 2 간격 행렬 (0, 2, 4, 6, 8)
# arange(start, stop, step) : stop인 10은 포함되지 않습니다.
arange_array = np.arange(0, 10, 2)

# 3. 0부터 1 사이를 5개로 균등하게 나눈 행렬
# linspace(start, stop, num) : stop인 1을 포함하여 num개의 데이터를 만듭니다.
linspace_array = np.linspace(0, 1, 5)

# 결과 출력
print(f"1. zeros(2x3):\n{zeros_matrix}")
print(f"\n2. arange(0, 10, 2): {arange_array}")
print(f"\n3. linspace(0, 1, 5): {linspace_array}")

1. zeros(2x3):
[[0. 0. 0.]
 [0. 0. 0.]]

2. arange(0, 10, 2): [0 2 4 6 8]

3. linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [9]:
# TODO 3: 2x3 크기에 1로 채운 행렬, 2x3에 7을 채운 행렬, 3x3 크기의 단위행렬, 
# 2x3 크기의 0-9 범위 랜덤 정수 행렬, 2x3 크기의 정규분포 난수 행렬을 출력해봅시다.
# 1. 2x3 크기에 1로 채운 행렬
ones_matrix = np.ones((2, 3))

# 2. 2x3 크기에 특정 값(7)을 채운 행렬
full_matrix = np.full((2, 3), 7)

# 3. 3x3 크기의 단위행렬 (Identity Matrix)
# 대각선은 1, 나머지는 0인 정사각형 행렬입니다.
eye_matrix = np.eye(3)

# 4. 2x3 크기의 0~9 범위 랜덤 정수 행렬
# randint(low, high, size): high(10)는 포함되지 않습니다.
rand_int_matrix = np.random.randint(0, 10, size=(2, 3))

# 5. 2x3 크기의 정규분포(Normal Distribution) 난수 행렬
# 평균 0, 표준편차 1인 표준정규분포에서 값을 추출합니다.
randn_matrix = np.random.randn(2, 3)

# 결과 출력
print(f"1. ones(2x3):\n{ones_matrix}")
print(f"\n2. full(2x3, 7):\n{full_matrix}")
print(f"\n3. eye(3):\n{eye_matrix}")
print(f"\n4. randint(0, 10, (2,3)):\n{rand_int_matrix}")
print(f"\n5. randn(2, 3):\n{randn_matrix}")

1. ones(2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

2. full(2x3, 7):
[[7 7 7]
 [7 7 7]]

3. eye(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. randint(0, 10, (2,3)):
[[5 4 0]
 [7 1 6]]

5. randn(2, 3):
[[-1.10354878 -0.88729318  0.42453947]
 [-0.31714867  0.98138721  1.72669905]]


</br>

## 인덱싱과 슬라이싱 (Indexing & Slicing)

In [10]:
# TODO 4: 1부터 9까지 3x3 크기의 행렬을 matrix에 저장하고,
#         - 0행 1열
#         - 1행 전체
#         - 2열 전체
#         - 0-1행, 1-2열 2x2 크기의 부분행렬
#         을 출력해봅시다.
# 1. 1부터 9까지 3x3 행렬 생성
matrix = np.arange(1, 10).reshape(3, 3) # 또는 np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"원본 행렬:\n{matrix}\n")

# 2. 0행 1열 (단일 원소 추출)
# 0부터 시작하므로 첫 번째 행의 두 번째 값을 가져옵니다.
element = matrix[0, 1] # matrix[0][1] 이렇게도 가능

# 3. 1행 전체
# : 하나만 쓰면 해당 축의 전체를 의미합니다.
row_1 = matrix[1, :]

# 4. 2열 전체
# 행 부분에 :를 넣고 열 부분에 2를 넣습니다.
col_2 = matrix[:, 2]

# 5. 0~1행, 1~2열 2x2 크기의 부분행렬
# 슬라이싱 [시작:끝]에서 '끝' 인덱스는 포함되지 않습니다.
sub_matrix = matrix[0:2, 1:3]

# 결과 출력
print(f"1. 0행 1열: {element}")
print(f"2. 1행 전체: {row_1}")
print(f"3. 2열 전체: {col_2}")
print(f"4. 부분 행렬 (2x2):\n{sub_matrix}")

원본 행렬:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1. 0행 1열: 2
2. 1행 전체: [4 5 6]
3. 2열 전체: [3 6 9]
4. 부분 행렬 (2x2):
[[2 3]
 [5 6]]


</br>

### 불리언 인덱싱 (Boolean Indexing)

In [11]:
# TODO 5: 10, 25, 30, 45, 50 데이터를 1x5 크기의 행렬을 array에 저장하고, 30을 초과하는 조건을 생성하여 필터링된 결과를 출력해봅시다.
# 1. 데이터 저장
array = np.array([10, 25, 30, 45, 50])

# 2. 30을 초과하는 조건 생성
# 이 결과는 [False, False, False, True, True] 형태의 논리 배열이 됩니다.
condition = array > 30

# 3. 조건을 사용하여 필터링
filtered_result = array[condition]

# 결과 출력
print(f"원본 데이터: {array}")
print(f"조건 결과 (Boolean): {condition}")
print(f"필터링 결과 (30 초과): {filtered_result}")

원본 데이터: [10 25 30 45 50]
조건 결과 (Boolean): [False False False  True  True]
필터링 결과 (30 초과): [45 50]


</br>

## reshape과 차원 변환
> `reshape`은 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">데이터를 유지하면서 배열의 형태를 변경</mark>합니다.

In [12]:
# TODO 6: arange를 이용하여 0부터 11을 array에 저장하고, 3x4 크기로 변환하여 matrix에 저장 후 결과를 출력해봅시다.
# 1. 0부터 11까지 데이터 생성 (총 12개)
array = np.arange(12)

# 2-1. 3x4 크기로 변환하여 matrix에 저장
# 전체 원소 개수가 12개(3 * 4)로 일치해야 변환이 가능합니다.
# 원소의 개수와 새로만든 배열의 크기가 다르다면 오류 발생
# matrix = array.reshape(3, 4)

# 2-2. 열(Column) 개수를 4개로 고정하고, 행(Row)은 자동으로 계산 (-1)
# 12 / 4 = 3이므로, 자동으로 3x4 행렬이 됩니다.
matrix1 = array.reshape(-1, 4)

# 3. 행(Row) 개수를 4개로 고정하고, 열(Column)은 자동으로 계산 (-1)
# 12 / 4 = 3이므로, 자동으로 4x3 행렬이 됩니다.
matrix2 = array.reshape(4, -1)

# 결과 출력
print("--- 원본 데이터 ---")
print(array)

print("\n--- matrix1 (열 4개 고정, 행 자동 계산) ---")
print(matrix1)
print(f"Shape: {matrix1.shape}") # (3, 4)

print("\n--- matrix2 (행 4개 고정, 열 자동 계산) ---")
print(matrix2)
print(f"Shape: {matrix2.shape}") # (4, 3)

--- 원본 데이터 ---
[ 0  1  2  3  4  5  6  7  8  9 10 11]

--- matrix1 (열 4개 고정, 행 자동 계산) ---
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

--- matrix2 (행 4개 고정, 열 자동 계산) ---
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)


💡reshape 주의
> 변환 전후의 전체 요소 수가 같아야 합니다.</br>
> `-1`을 사용하면 해당 차원의 크기를 자동 계산합니다.

</br>

## 배열 변환 (Array Transformation)

<table style="width:100%">
  <thead>
    <tr>
      <th style="text-align:center">함수</th>
      <th>설명</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="text-align:center"><code>arr.flatten()</code></td><td>다차원 배열을 1차원으로 변환</td></tr>
    <tr><td style="text-align:center"><code>arr.T</code> / <code>np.transpose(arr)</code></td><td>행과 열을 전치(transpose)</td></tr>
    <tr><td style="text-align:center"><code>np.tile(arr, reps)</code></td><td>배열을 지정한 횟수만큼 반복</td></tr>
    <tr><td style="text-align:center"><code>arr.astype(dtype)</code></td><td>배열 원소의 데이터 타입 변환</td></tr>
  </tbody>
</table>

In [13]:
# TODO 7: 2x3 행렬에 1부터 6까지 저장하고,
#  - 1차원 변환
#  - 전치 행렬
#  - 열 방향 2배 반복
#  - 1x3 크기의 1.7, 2.3, 3.9 행렬을 정수 타입 변환 행렬 을 출력해봅시다.
# 1. 2x3 행렬에 1부터 6까지 저장
matrix = np.array([[1,2,3], [4,5,6]])
print(f"원본 행렬:\n{matrix}\n")

# 2. 1차원 변환 (Flatten), reshape로도 충분
flattened = matrix.flatten()

# 3. 전치 행렬 (Transpose)
# 행과 열을 바꿉니다. (2x3 -> 3x2)
transposed = matrix.T  # 또는 np.transpose(matrix)

# 4. 열 방향 2배 반복 (Tile)
# np.tile을 사용하면 전체 배열을 원하는 방향으로 복사할 수 있습니다.
# (1, 2)는 행 방향 1번, 열 방향 2번 반복하라는 의미입니다.
repeated = np.tile(matrix, (1, 2))

# 5. 실수 행렬 생성 및 정수 타입 변환 (astype)
floats = np.array([1.7, 2.3, 3.9])
# astype을 사용하면 데이터 타입을 강제로 변경합니다 (소수점 버림). 정수를 실수로 바꾸는것도 가능
integers = floats.astype(int)

# 결과 출력
print(f"1. 1차원 변환: {flattened}")
print(f"2. 전치 행렬:\n{transposed}")
print(f"3. 열 방향 2배 반복:\n{repeated}")
print(f"4. 실수 행렬: {floats}")
print(f"5. 정수 타입 변환: {integers}")

원본 행렬:
[[1 2 3]
 [4 5 6]]

1. 1차원 변환: [1 2 3 4 5 6]
2. 전치 행렬:
[[1 4]
 [2 5]
 [3 6]]
3. 열 방향 2배 반복:
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
4. 실수 행렬: [1.7 2.3 3.9]
5. 정수 타입 변환: [1 2 3]


</br>

## 배열 연산 (Vectorized Operations)
> NumPy는 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">반복문 없이 배열 전체에 연산</mark>을 적용합니다.

In [14]:
# TODO 8: array_a에 1x3 크기의 1, 2, 3 행렬을, array_b에 1x3 크기의 4, 5, 6 행렬을 저장하고 합, 곱, 제곱, 내적을 출력해봅시다.
# 1. 두 배열 저장
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# 2. 합 (Addition)
# 각 위치의 원소끼리 더해집니다.
add_result = array_a + array_b

# 3. 곱 (Multiplication - Element-wise)
# 각 위치의 원소끼리 곱해집니다. (1*4, 2*5, 3*6)
mul_result = array_a * array_b

# 4. 제곱 (Power)
# array_a의 모든 원소를 제곱합니다.
pow_result = array_a ** 2

# 5. 내적 (Dot Product)
# 대응하는 원소끼리 곱한 뒤 모두 더한 값입니다. (1*4 + 2*5 + 3*6 = 4 + 10 + 18)
dot_result = np.dot(array_a, array_b)
# 또는 array_a @ array_b 도 가능합니다.

# 결과 출력
print(f"array_a: {array_a}")
print(f"array_b: {array_b}")
print("-" * 30)
print(f"1. 합: {add_result}")
print(f"2. 곱 (원소별): {mul_result}")
print(f"3. 제곱 (a^2): {pow_result}")
print(f"4. 내적 (Dot Product): {dot_result}")

array_a: [1 2 3]
array_b: [4 5 6]
------------------------------
1. 합: [5 7 9]
2. 곱 (원소별): [ 4 10 18]
3. 제곱 (a^2): [1 4 9]
4. 내적 (Dot Product): 32


In [15]:
# TODO 9: 1x5 크기의 3, 1, 4, 1, 5 데이터를 array에 저장하고, 최댓값, 최솟값, 최솟값 인덱스, 정렬 결과를 출력해봅시다.
# 1. 1x5 크기의 데이터 생성
array = np.array([3, 1, 4, 1, 5])

# 2. 최댓값 (Max)
max_val = array.max()

# 3. 최솟값 (Min)
min_val = array.min()

# 4. 최솟값의 인덱스 (Argmin)
# 가장 작은 값이 처음 나타나는 위치의 인덱스를 반환합니다.
min_idx = array.argmin()

# 5. 정렬 결과 (Sort)
# 기본적으로 오름차순으로 정렬된 복사본을 반환합니다.
# 원본을 정렬하려면 array.sort()
sorted_array = np.sort(array)

# 결과 출력
print(f"원본 배열: {array}")
print(f"최댓값: {max_val}")
print(f"최솟값: {min_val}")
print(f"최솟값 인덱스: {min_idx}")
print(f"정렬 결과: {sorted_array}")

원본 배열: [3 1 4 1 5]
최댓값: 5
최솟값: 1
최솟값 인덱스: 1
정렬 결과: [1 1 3 4 5]


</br>

## 브로드캐스팅 (Broadcasting)
> 크기가 다른 배열 간 연산 시 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">작은 배열을 자동으로 확장</mark>하는 규칙입니다.

In [3]:
# TODO 10: matrix에 2x3 크기의 행렬에 1부터 6까지 행렬을 저장하고, 
# vector에 1x3 크기의 행렬에 10, 20, 30을 저장한 후 matrix + vector 브로드캐스팅 결과를 출력해봅시다.
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix + vector

print("--- Matrix (2x3) ---")
print(matrix)
print("\n--- Vector (1x3) ---")
print(vector)
print("\n--- Result (Broadcasting) ---")
print(result)

--- Matrix (2x3) ---
[[1 2 3]
 [4 5 6]]

--- Vector (1x3) ---
[10 20 30]

--- Result (Broadcasting) ---
[[11 22 33]
 [14 25 36]]


💡브로드캐스팅 규칙
> 뒤쪽 차원부터 비교하여 크기가 같거나 하나가 1이면 브로드캐스팅이 적용됩니다.

</br>

## 집계 함수 (Aggregation)

In [4]:
# TODO 11: array에 2x3 크기의 행렬에 1부터 6까지 저장하고, 전체 합, 열별 합, 행별 평균, 최댓값 인덱스를 출력해봅시다.
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

total_sum = np.sum(matrix) # 전체 합
col_sum = np.sum(matrix, axis=0) # 열별 합 (axis=0), 위에서 아래 방향으로 더함 (결과는 각 열의 합인 3개의 값이 나옴)
row_avg = np.mean(matrix, axis=1) # 행별 평균 (axis=1), 왼쪽에서 오른쪽 방향으로 평균 (결과는 각 행의 평균인 2개의 값이 나옴)
max_idx = np.argmax(matrix) # 전체 최댓값의 인덱스, 2차원 배열이라도 flatten(1차원) 기준으로 몇 번째인지 알려줌

# 결과 출력
print(f"원본 행렬:\n{matrix}")
print(f"1. 전체 합: {total_sum}")
print(f"2. 열별 합 (axis=0): {col_sum}")
print(f"3. 행별 평균 (axis=1): {row_avg}")
print(f"4. 최댓값 인덱스: {max_idx}")

원본 행렬:
[[1 2 3]
 [4 5 6]]
1. 전체 합: 21
2. 열별 합 (axis=0): [5 7 9]
3. 행별 평균 (axis=1): [2. 5.]
4. 최댓값 인덱스: 5


💡axis 파라미터
> `axis=0`은 행 방향(열별 집계), `axis=1`은 열 방향(행별 집계)입니다.

</br>

## 수학 함수 및 비교 (Math Functions & Comparison)
> NumPy는 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">원소별 수학 함수</mark>와 배열 비교 함수를 제공합니다.

<table style="width:100%">
  <thead>
    <tr>
      <th style="text-align:center">함수</th>
      <th>설명</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="text-align:center"><code>np.sin(arr)</code> / <code>np.cos(arr)</code></td><td>원소별 삼각함수 적용</td></tr>
    <tr><td style="text-align:center"><code>np.exp(arr)</code></td><td>원소별 지수함수 (e^x) 적용</td></tr>
    <tr><td style="text-align:center"><code>np.log(arr)</code></td><td>원소별 자연로그 적용</td></tr>
    <tr><td style="text-align:center"><code>np.array_equal(a, b)</code></td><td>두 배열이 완전히 같은지 비교</td></tr>
    <tr><td style="text-align:center"><code>np.allclose(a, b)</code></td><td>두 배열이 허용 오차 내에서 같은지 비교</td></tr>
  </tbody>
</table>

In [5]:
# TODO 12:
#  - 1x3 크기의 행렬에 0, π/2, π을 angles에 저장하고 sin, cos 출력
#  - 1x3 크기의 행렬에 1, 2, 3을 vals에 저장하고 지수, 로그를 출력
#  - a, b 비교, a, c 비교, 허용 오차 내 a, c 비교
#  를 출력해봅시다.

# 1. 삼각함수 (0, π/2, π)
# np.pi는 원주율(3.1415...) 상수를 제공합니다.
angles = np.array([0, np.pi/2, np.pi])
print(f"--- 삼각함수 ---")
print(f"Sin: {np.sin(angles)}")
print(f"Cos: {np.cos(angles)}")

# 2. 지수 및 로그 함수 (1, 2, 3)
vals = np.array([1, 2, 3])
print(f"\n--- 지수와 로그 ---")
print(f"Exp (e^x): {np.exp(vals)}")
print(f"Log (자연로그): {np.log(vals)}")

# 3. 배열 비교 (a, b, c)
a = np.array([1.1, 2.2, 3.3])
b = np.array([1.1, 2.2, 3.3])
c = np.array([1.1000000001, 2.2000000001, 3.3000000001])

print(f"\n--- 비교 연산 ---")
print(f"a == b (정확히 일치): {np.array_equal(a, b)}")
print(f"a == c (정확히 일치): {np.array_equal(a, c)}")

# 허용 오차(Tolerance) 내에서 비교 (부동 소수점 오차 해결)
print(f"a ≈ c (허용 오차 내 일치): {np.allclose(a, c)}")

--- 삼각함수 ---
Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]

--- 지수와 로그 ---
Exp (e^x): [ 2.71828183  7.3890561  20.08553692]
Log (자연로그): [0.         0.69314718 1.09861229]

--- 비교 연산 ---
a == b (정확히 일치): True
a == c (정확히 일치): False
a ≈ c (허용 오차 내 일치): True


💡array_equal vs allclose
> `np.array_equal()`은 값이 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">정확히 일치</mark>해야 True를 반환합니다.</br>
> `np.allclose()`는 부동소수점 오차를 허용하므로 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">수치 계산 결과 비교</mark>에 적합합니다.